// <auto-generated />
namespace User.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FormTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FormTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202211151324042_FormTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
